default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>
  port: <%= ENV.fetch("MYSQL_PORT", 3306) %>

development:
  <<: *default
  database: smart_rowing_development

test:
  <<: *default
  database: smart_rowing_test

production:
  <<: *default
  database: smart_rowing_production
  username: <%= ENV.fetch("MYSQL_USER", "smart_rowing") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
